apiVersion: v1
kind: Service
metadata:
  name: bonus-generator-service
spec:
  type: NodePort
  selector:
    app: bonus-generator
  ports:
    - port: 80
      targetPort: 8083
      nodePort: 30007
